version: '3'

services:
  db:
    container_name: example_db
    image: postgres:13
    env_file:
      - docker-compose.env

  app:
    container_name: example_app
    image: ghcr.io/yothinix/earthly-thurstech:latest
    entrypoint: /entrypoint.sh
    env_file:
      - docker-compose.env
    volumes:
      - ./example/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
